"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.keras.layers.legacy_rnn.rnn_cell_impl import BasicLSTMCell, BasicRNNCell, DeviceWrapper, DropoutWrapper, GRUCell, LSTMCell, LSTMStateTuple, MultiRNNCell, RNNCell, ResidualWrapper
from tensorflow.python.util import module_wrapper as _module_wrapper

"""Public API for tf._api.v2.nn.rnn_cell namespace
"""
if not isinstance(_sys.modules[__name__], _module_wrapper.TFModuleWrapper):
  ...
