"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.eager.backprop import GradientTape
from tensorflow.python.eager.forwardprop import ForwardAccumulator

"""Public API for tf._api.v2.autodiff namespace
"""
