"""
This type stub file was generated by pyright.
"""

"""A Python interface for creating TensorFlow servers."""
def list_local_devices(session_config=...): # -> list[Any]:
  """List the available devices available in the local process.

  Args:
    session_config: a session config proto or None to use the default config.

  Returns:
    A list of `DeviceAttribute` protocol buffers.
  """
  ...

