"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.framework.config import get_optimizer_experimental_options as get_experimental_options, get_optimizer_jit as get_jit, set_optimizer_experimental_options as set_experimental_options, set_optimizer_jit as set_jit
from tensorflow.python.util import module_wrapper as _module_wrapper

"""Public API for tf._api.v2.config.optimizer namespace
"""
if not isinstance(_sys.modules[__name__], _module_wrapper.TFModuleWrapper):
  ...
