"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.types.data import DatasetV2 as Dataset

"""Public API for tf._api.v2.__internal__.types.data namespace
"""
