services:
  db:
    image: postgres
    restart: always
    user: postgres
    env_file: ./.env
    volumes:
      - ./stor/pg:/var/lib/postgresql:rw
      - ./db:/docker-entrypoint-initdb.d:ro
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net

volumes:
  pgdata:
networks:
  net:
    driver: bridge