"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow._api.v2.compat.v2.dtypes import experimental
from tensorflow.python.framework.dtypes import DType, QUANTIZED_DTYPES, as_dtype, bfloat16, bool, complex128, complex64, double, float16, float32, float64, half, int16, int32, int64, int8, qint16, qint32, qint8, quint16, quint8, resource, string, uint16, uint32, uint64, uint8, variant
from tensorflow.python.ops.math_ops import cast, complex, saturate_cast

"""Public API for tf._api.v2.dtypes namespace
"""
