"""
This type stub file was generated by pyright.
"""

"""Stub to make pywrap metrics wrapper accessible."""
def retrieve_collected_errors(): # -> list[Any]:
  """Returns and clears the list of collected errors in ErrorCollector.

  The RetrieveCollectedErrors function in C++ returns a list of serialized proto
  messages. This function will convert them to ConverterErrorData instances.

  Returns:
    A list of ConverterErrorData.
  """
  ...

