"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Dict, Mapping, Optional
from tensorflow.python.checkpoint import graph_view as graph_view_lib
from tensorflow.python.trackable import base

"""Extracts tensors for checkpointing while updating a TrackableObjectGraph.

The tensors are extracted from `Trackable._serialize_to_tensors`.
"""
_TrackableData = ...
def serialize_graph_view(graph_view: graph_view_lib.ObjectGraphView, object_map: Optional[Mapping[base.Trackable, base.Trackable]] = ..., call_with_mapped_captures: Optional[Callable[..., Any]] = ..., cache: Optional[Dict[base.Trackable, Any]] = ...) -> ...:
  """Gathers serialization objects, and creates a TrackableObjectGraph proto."""
  ...

