"""
This type stub file was generated by pyright.
"""

from tensorflow.python.training.queue_runner import *
from tensorflow.python.training.input import *
from tensorflow.core.example.example_pb2 import *
from tensorflow.core.example.feature_pb2 import *
from tensorflow.core.protobuf.saver_pb2 import *
from tensorflow.python.training.learning_rate_decay import *

"""Support for training models.

See the [Training](https://tensorflow.org/api_guides/python/train) guide.
"""
