"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.util.dispatch import GlobalOpDispatcher, OpDispatcher, add_dispatch_support

"""Public API for tf._api.v2.__internal__.dispatch namespace
"""
