"""
This type stub file was generated by pyright.
"""

from tensorflow.python.framework import func_graph

"""FuncGraphs for V2 control flow."""
class ControlFlowFuncGraph(func_graph.FuncGraph):
  """Contains control flow-specific FuncGraph logic."""
  def __init__(self, *args, **kwargs) -> None:
    ...
  


class CondBranchFuncGraph(ControlFlowFuncGraph):
  """FuncGraph for branches of tf.cond().

  This is used to distinguish cond branches from other functions.
  """
  ...


class WhileCondFuncGraph(ControlFlowFuncGraph):
  """FuncGraph for the condition of tf.while_loop().

  This is used to distinguish while conditions from other functions.
  """
  ...


class WhileBodyFuncGraph(ControlFlowFuncGraph):
  """FuncGraph for the body of tf.while_loop().

  This is used to distinguish while bodies from other functions.
  """
  ...


