"""
This type stub file was generated by pyright.
"""

from typing import Any

def TF_OptimizeGraph(*args, **kwargs) -> Any:
    ...

def TF_OptimizeGraphSerialized(arg0, arg1: str, arg2: str, arg3: bool, arg4: str, arg5: bool) -> bytes:
    ...

