"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow._api.v2.compat.v1.distribute import cluster_resolver, experimental
from tensorflow.python.distribute.cross_device_ops import CrossDeviceOps, HierarchicalCopyAllReduce, NcclAllReduce, ReductionToOneDevice
from tensorflow.python.distribute.distribute_lib import InputContext, InputReplicationMode, ReplicaContextV1 as ReplicaContext, RunOptions, StrategyExtendedV1 as StrategyExtended, StrategyV1 as Strategy, experimental_set_strategy, get_replica_context, get_strategy, has_strategy, in_cross_replica_context
from tensorflow.python.distribute.distribute_utils import get_loss_reduction
from tensorflow.python.distribute.mirrored_strategy import MirroredStrategyV1 as MirroredStrategy
from tensorflow.python.distribute.one_device_strategy import OneDeviceStrategyV1 as OneDeviceStrategy
from tensorflow.python.distribute.reduce_util import ReduceOp
from tensorflow.python.training.server_lib import Server
from tensorflow.python.util import module_wrapper as _module_wrapper

"""Public API for tf._api.v2.distribute namespace
"""
if not isinstance(_sys.modules[__name__], _module_wrapper.TFModuleWrapper):
  ...
