"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow._api.v2.compat.v2.lite.experimental import authoring
from tensorflow.lite.python.analyzer import ModelAnalyzer as Analyzer
from tensorflow.lite.python.interpreter import OpResolverType, load_delegate
from tensorflow.lite.tools.optimize.debugging.python.debugger import QuantizationDebugOptions, QuantizationDebugger

"""Public API for tf._api.v2.lite.experimental namespace
"""
