"""
This type stub file was generated by pyright.
"""

"""Optimizer utilities."""
def all_reduce_sum_gradients(grads_and_vars): # -> list[Any]:
  """Returns all-reduced gradients aggregated via summation.

  Args:
    grads_and_vars: List of (gradient, variable) pairs.

  Returns:
    List of (gradient, variable) pairs where gradients have been all-reduced.
  """
  ...

def filter_empty_gradients(grads_and_vars): # -> tuple[Any, ...]:
  """Filter out `(grad, var)` pairs that have a gradient equal to `None`."""
  ...

def make_gradient_clipnorm_fn(clipnorm): # -> Callable[..., Any] | Callable[..., list[tuple[IndexedSlices | Any | defaultdict[Any, Any] | list[Any] | object | None, Any]]]:
  """Creates a gradient transformation function for clipping by norm."""
  ...

def make_global_gradient_clipnorm_fn(clipnorm): # -> Callable[..., Any] | Callable[..., list[tuple[IndexedSlices | Any, Any]]]:
  """Creates a gradient transformation function for clipping by norm."""
  ...

def make_gradient_clipvalue_fn(clipvalue): # -> Callable[..., Any] | Callable[..., list[tuple[IndexedSlices | Any, Any]]]:
  """Creates a gradient transformation function for clipping by value."""
  ...

def strategy_supports_no_merge_call(): # -> bool:
  """Returns if the current Strategy can operate in pure replica context."""
  ...

