"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.saved_model.revived_types import VersionedTypeRegistration, get_setter, register_revived_type, registered_identifiers

"""Public API for tf._api.v2.__internal__.saved_model.load namespace
"""
