"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.platform.resource_loader import get_data_files_path, get_path_to_datafile, get_root_dir_with_all_resources, load_resource, readahead_file_path
from tensorflow.python.util import module_wrapper as _module_wrapper

"""Public API for tf._api.v2.resource_loader namespace
"""
if not isinstance(_sys.modules[__name__], _module_wrapper.TFModuleWrapper):
  ...
