"""
This type stub file was generated by pyright.
"""

from tensorflow.python.data.ops import dataset_ops

"""The implementation of `tf.data.Dataset.cache`."""
class CacheDataset(dataset_ops.UnaryUnchangedStructureDataset):
  """A `Dataset` that caches elements of its input."""
  def __init__(self, input_dataset, filename, name=...) -> None:
    """See `Dataset.cache()` for details."""
    ...
  


