"""
This type stub file was generated by pyright.
"""

from tensorflow.python.data.ops import dataset_ops

"""The implementation of `tf.data.Dataset.from_tensors`."""
class _TensorDataset(dataset_ops.DatasetSource):
  """A `Dataset` with a single element."""
  def __init__(self, element, name=...) -> None:
    """See `tf.data.Dataset.from_tensors` for details."""
    ...
  
  @property
  def element_spec(self): # -> TypeSpec | Mapping[Any, Any] | defaultdict[Any, Any] | Any | tuple[Any, ...] | tuple[TypeSpec | Mapping[Any, Any] | defaultdict[Any, Any] | Any | tuple[Any, ...] | None, ...] | None:
    ...
  


