"""
This type stub file was generated by pyright.
"""

from tensorflow.python.data.ops import dataset_ops

"""The implementation of `tf.data.Dataset.prefetch`."""
class _PrefetchDataset(dataset_ops.UnaryUnchangedStructureDataset):
  """A `Dataset` that asynchronously prefetches its input."""
  def __init__(self, input_dataset, buffer_size, slack_period=..., name=...) -> None:
    """See `Dataset.prefetch()` for details."""
    ...
  


