"""
This type stub file was generated by pyright.
"""

from tensorflow.python.data.ops import dataset_ops

"""The implementation of `tf.data.Dataset.range`."""
class _RangeDataset(dataset_ops.DatasetSource):
  """A `Dataset` of a step separated range of values."""
  def __init__(self, *args, **kwargs) -> None:
    """See `Dataset.range()` for details."""
    ...
  
  @property
  def element_spec(self): # -> TensorSpec:
    ...
  


