"""
This type stub file was generated by pyright.
"""

def GpuSupportsHalfMatMulAndConv() -> bool:
    ...

def IsAArch32Available() -> bool:
    ...

def IsAArch64Available() -> bool:
    ...

def IsBuiltWithNvcc() -> bool:
    ...

def IsBuiltWithROCm() -> bool:
    ...

def IsBuiltWithXLA() -> bool:
    ...

def IsGoogleCudaEnabled() -> bool:
    ...

def IsMklEnabled() -> bool:
    ...

def IsPowerPCAvailable() -> bool:
    ...

def IsSystemZAvailable() -> bool:
    ...

def IsX86Available() -> bool:
    ...

