"""
This type stub file was generated by pyright.
"""

from tensorflow.python.util import _tf_stack

"""Functions used to extract and analyze stacks.  Faster than Python libs."""
_get_thread_key = ...
_source_mapper_stacks = ...
_source_filter_stacks = ...
class StackTraceTransform:
  """Base class for stack trace transformation functions."""
  _stack_dict = ...
  _thread_key = ...
  def __enter__(self): # -> Self:
    ...
  
  def __exit__(self, unused_type, unused_value, unused_traceback): # -> None:
    ...
  
  def update(self):
    ...
  


class StackTraceMapper(StackTraceTransform):
  """Allows remapping traceback information to different source code."""
  _stack_dict = ...
  def __init__(self) -> None:
    ...
  
  def update(self): # -> None:
    ...
  
  def get_effective_source_map(self):
    """Returns a map (filename, lineno) -> (filename, lineno, function_name)."""
    ...
  


EMPTY_DICT = ...
class SentinelMapper(StackTraceMapper):
  def get_effective_source_map(self): # -> dict[Any, Any]:
    ...
  


class StackTraceFilter(StackTraceTransform):
  """Allows filtering traceback information by removing superfluous frames."""
  _stack_dict = ...
  def __init__(self) -> None:
    ...
  
  def update(self): # -> None:
    ...
  
  def get_filtered_filenames(self):
    ...
  


EMPTY_SET = ...
class SentinelFilter(StackTraceFilter):
  def get_filtered_filenames(self): # -> frozenset[Any]:
    ...
  


class CurrentModuleFilter(StackTraceFilter):
  """Filters stack frames from the module where this is used (best effort)."""
  def __init__(self) -> None:
    ...
  
  def get_filtered_filenames(self): # -> frozenset[str | None]:
    ...
  


def extract_stack(stacklevel=...): # -> StackTrace:
  """An eager-friendly alternative to traceback.extract_stack.

  Args:
    stacklevel: number of initial frames to skip when producing the stack.

  Returns:
    A list-like FrameSummary containing StackFrame-like objects, which are
    namedtuple-like objects with the following fields: filename, lineno, name,
    line, meant to masquerade as traceback.FrameSummary objects.
  """
  ...

def LoadTracesFromDebugInfo(debug_info): # -> dict[str, StackTrace]:
  ...

class GraphDebugInfoBuilder(_tf_stack.GraphDebugInfoBuilder):
  def AppendGraphDebugInfo(self, fn_name, fn_debug_info): # -> None:
    ...
  
  def Build(self):
    ...
  


StackSummary = _tf_stack.StackTrace
FrameSummary = _tf_stack.StackFrame
