"""
This type stub file was generated by pyright.
"""

from tensorflow.python._pywrap_mlir import *

"""Python module for MLIR functions exported by pybind11."""
def import_graphdef(graphdef, pass_pipeline, show_debug_info, input_names=..., input_data_types=..., input_data_shapes=..., output_names=...): # -> str:
  ...

def import_function(concrete_function, pass_pipeline, show_debug_info): # -> str:
  ...

def experimental_convert_saved_model_to_mlir(saved_model_path, exported_names, show_debug_info): # -> str:
  ...

def experimental_convert_saved_model_v1_to_mlir_lite(saved_model_path, exported_names, tags, upgrade_legacy, show_debug_info): # -> str:
  ...

def experimental_convert_saved_model_v1_to_mlir(saved_model_path, exported_names, tags, lift_variables, include_variables_in_initializers, upgrade_legacy, show_debug_info): # -> str:
  ...

def experimental_run_pass_pipeline(mlir_txt, pass_pipeline, show_debug_info): # -> str:
  ...

def experimental_write_bytecode(filename, mlir_txt): # -> None:
  ...

def experimental_tflite_to_tosa_bytecode(flatbuffer, bytecode, use_external_constant=..., ordered_input_arrays=..., ordered_output_arrays=...): # -> None:
  ...

