"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.saved_model.utils_impl import build_tensor_info, get_tensor_from_tensor_info
from tensorflow.python.util import module_wrapper as _module_wrapper

"""Public API for tf._api.v2.saved_model.utils namespace
"""
if not isinstance(_sys.modules[__name__], _module_wrapper.TFModuleWrapper):
  ...
