"""
This type stub file was generated by pyright.
"""

from google.protobuf import descriptor as _descriptor
from tensorflow.compiler.xla.tsl.protobuf.test_log_pb2 import *

"""Generated protocol buffer code."""
_sym_db = ...
DESCRIPTOR = ...
if _descriptor._USE_C_DESCRIPTORS == False:
  ...
