"""
This type stub file was generated by pyright.
"""

"""Autograph utility functions for polymorphic_function."""
def py_func_from_autograph(python_func, autograph_options=...):
  """Compile a python function using autograph, for use with FuncGraph.

  Args:
    python_func: the Python function to compile.
    autograph_options: additional knobs to control when `autograph=True`.
      See https://www.tensorflow.org/guide/autograph for more information.
  Returns:
    python_func, converted using autograph.
  """
  ...

