"""
This type stub file was generated by pyright.
"""

"""Module for the TFMethodTarget Class."""
class TfMethodTarget:
  """Binding target for methods replaced by function and defun."""
  __slots__ = ...
  def __init__(self, target, original_python_function) -> None:
    ...
  
  @property
  def target(self):
    ...
  
  @property
  def target_class(self):
    ...
  
  def call(self, args, kwargs):
    ...
  


