"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.lite.python.lite_constants import FLOAT, FLOAT16, GRAPHVIZ_DOT, INT16, INT32, INT64, INT8, QUANTIZED_UINT8, STRING, TFLITE
from tensorflow.python.util import module_wrapper as _module_wrapper

"""Public API for tf._api.v2.lite.constants namespace
"""
if not isinstance(_sys.modules[__name__], _module_wrapper.TFModuleWrapper):
  ...
