"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.lib.io.file_io import copy_v2 as copy, create_dir_v2 as mkdir, delete_file_v2 as remove, delete_recursively_v2 as rmtree, file_exists_v2 as exists, get_matching_files_v2 as glob, get_registered_schemes, is_directory_v2 as isdir, join, list_directory_v2 as listdir, recursive_create_dir_v2 as makedirs, rename_v2 as rename, stat_v2 as stat, walk_v2 as walk
from tensorflow.python.platform.gfile import GFile
from tensorflow.python.util import module_wrapper as _module_wrapper

"""Public API for tf._api.v2.io.gfile namespace
"""
if not isinstance(_sys.modules[__name__], _module_wrapper.TFModuleWrapper):
  ...
