"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Tuple

"""Utilities for the trace_type module."""
def is_namedtuple(obj): # -> bool:
  ...

def is_attrs(obj): # -> bool:
  ...

def is_np_ndarray(value): # -> bool:
  ...

def cast_and_return_whether_casted(trace_types, values, context) -> Tuple[List[Any], bool]:
  ...

