"""
This type stub file was generated by pyright.
"""

import multiprocessing

"""Library for multi-process testing."""
def is_oss(): # -> bool:
  """Returns whether the test is run under OSS."""
  ...

class _AbslProcess:
  """A process that runs using absl.app.run."""
  def __init__(self, *args, **kwargs) -> None:
    ...
  


if _is_enabled():
  class AbslForkServerProcess(_AbslProcess, multiprocessing.context.ForkServerProcess):
    """An absl-compatible Forkserver process.

    Note: Forkserver is not available in windows.
    """
    ...
  
  
  class AbslForkServerContext(multiprocessing.context.ForkServerContext):
    _name = ...
    Process = AbslForkServerProcess
  
  
  multiprocessing = ...
  Process = multiprocessing.Process
else:
  class Process:
    """A process that skips test (until windows is supported)."""
    def __init__(self, *args, **kwargs) -> None:
      ...
    
  
  
_test_main_called = ...
def test_main(): # -> None:
  """Main function to be called within `__main__` of a test file."""
  ...

def initialized(): # -> bool:
  """Returns whether the module is initialized."""
  ...

