"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow._api.v2.lookup import experimental
from tensorflow.python.ops.lookup_ops import KeyValueTensorInitializer, StaticHashTable, StaticVocabularyTable, TextFileIndex, TextFileInitializer

"""Public API for tf._api.v2.lookup namespace
"""
