"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.saved_model.signature_constants import CLASSIFY_INPUTS, CLASSIFY_METHOD_NAME, CLASSIFY_OUTPUT_CLASSES, CLASSIFY_OUTPUT_SCORES, DEFAULT_SERVING_SIGNATURE_DEF_KEY, PREDICT_INPUTS, PREDICT_METHOD_NAME, PREDICT_OUTPUTS, REGRESS_INPUTS, REGRESS_METHOD_NAME, REGRESS_OUTPUTS
from tensorflow.python.util import module_wrapper as _module_wrapper

"""Public API for tf._api.v2.saved_model.signature_constants namespace
"""
if not isinstance(_sys.modules[__name__], _module_wrapper.TFModuleWrapper):
  ...
