"""
This type stub file was generated by pyright.
"""

from tensorflow.python.user_ops.ops.gen_user_ops import *
from tensorflow.python.util.tf_export import tf_export

"""All user ops."""
@tf_export(v1=['user_ops.my_fact'])
def my_fact(): # -> Any:
  """Example of overriding the generated code for an Op."""
  ...

