"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow.python.checkpoint.sharding.sharding_policies import MaxShardSizePolicy, ShardByTaskPolicy
from tensorflow.python.checkpoint.sharding.sharding_util import ShardableTensor, ShardingCallback
from tensorflow.python.trackable.python_state import PythonState
from tensorflow.python.training.experimental.loss_scale import DynamicLossScale, FixedLossScale, LossScale
from tensorflow.python.training.experimental.loss_scale_optimizer import MixedPrecisionLossScaleOptimizer
from tensorflow.python.training.experimental.mixed_precision import disable_mixed_precision_graph_rewrite_v1 as disable_mixed_precision_graph_rewrite, enable_mixed_precision_graph_rewrite_v1 as enable_mixed_precision_graph_rewrite
from tensorflow.python.util import module_wrapper as _module_wrapper

"""Public API for tf._api.v2.train.experimental namespace
"""
if not isinstance(_sys.modules[__name__], _module_wrapper.TFModuleWrapper):
  ...
