"""
This type stub file was generated by pyright.
"""

from tensorflow.python.trackable import base
from tensorflow.python.util.compat import collections_abc

"""Helpers for working with signatures in tf.saved_model.save."""
DEFAULT_SIGNATURE_ATTR = ...
SIGNATURE_ATTRIBUTE_NAME = ...
_NUM_DISPLAY_NORMALIZED_SIGNATURES = ...
def find_function_to_export(saveable_view): # -> Function | ConcreteFunction | None:
  """Function to export, None if no suitable function was found."""
  ...

def canonicalize_signatures(signatures): # -> tuple[dict[Any, Any], dict[Any, Any], dict[Any, Any]]:
  """Converts `signatures` into a dictionary of concrete functions."""
  ...

class _SignatureMap(collections_abc.Mapping, base.Trackable):
  """A collection of SavedModel signatures."""
  def __init__(self) -> None:
    ...
  
  def __getitem__(self, key):
    ...
  
  def __iter__(self): # -> Iterator[Any]:
    ...
  
  def __len__(self): # -> int:
    ...
  
  def __repr__(self): # -> str:
    ...
  


def create_signature_map(signatures): # -> _SignatureMap:
  """Creates an object containing `signatures`."""
  ...

def validate_augmented_graph_view(augmented_graph_view): # -> None:
  """Performs signature-related sanity checks on `augmented_graph_view`."""
  ...

