"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow._api.v2.quantization import experimental
from tensorflow.python.ops.gen_array_ops import fake_quant_with_min_max_args, fake_quant_with_min_max_args_gradient, fake_quant_with_min_max_vars, fake_quant_with_min_max_vars_gradient, fake_quant_with_min_max_vars_per_channel, fake_quant_with_min_max_vars_per_channel_gradient, quantized_concat
from tensorflow.python.ops.array_ops import dequantize, quantize, quantize_and_dequantize, quantize_and_dequantize_v2

"""Public API for tf._api.v2.quantization namespace
"""
