"""
This type stub file was generated by pyright.
"""

import sys as _sys
from tensorflow._api.v2.compat.v1.lite import constants, experimental
from tensorflow.lite.python.convert import OpsSet, toco_convert
from tensorflow.lite.python.interpreter import Interpreter
from tensorflow.lite.python.lite import Optimize, RepresentativeDataset, TFLiteConverter, TargetSpec, TocoConverter
from tensorflow.lite.python.op_hint import OpHint
from tensorflow.python.util import module_wrapper as _module_wrapper

"""Public API for tf._api.v2.lite namespace
"""
if not isinstance(_sys.modules[__name__], _module_wrapper.TFModuleWrapper):
  ...
